// Additive chapter 1 scenes. All coordinates are feet, in the school's 960x640 space.
const adventureImages={};
function adventureImage(name){if(!adventureImages[name]){const im=new Image();im.src='assets/kotoba-tower/'+name+'.webp?v=027-2';adventureImages[name]=im}return adventureImages[name]}
const maps={
 descent:{image:'ch1-descent-v2',name:'古い下り階段'},
 entry:{image:'ch1-entry-v2',name:'地下入口'},
 corridor:{image:'ch1-corridor-v2',name:'古い地下回廊'},
 central:{image:'ch1-central-v2',name:'中央回廊'},
 archive:{image:'ch1-archive-v2',name:'西側書庫跡'},
 record:{image:'ch1-record-v2',name:'記録の間'},
 joined:{image:'ch1-joined-v2',name:'奥の回廊'},
 memory:{image:'ch1-memory-v2',name:'静かな回廊'},
 bakuro:{image:'ch1-bakuro-v2',name:'広い石の間'},
 gate:{image:'ch1-gate-v2',name:'巨大石扉'},
 grass:{image:'ch1-grass',name:'見知らぬ草原'},
 village:{image:'ch1-village',name:'名前のない村'},
 shop:{image:'ch1-shop',name:'道具屋'}
};
Object.values(maps).forEach(m=>adventureImage(m.image));
['hero-current-battle','normal-enemy-field','normal-enemy-battle','ren-sheet','elder-man','elder-woman','shopkeeper','village-child','bakuro-small','bakuro-battle','cottage','village-shop','distant-tower','stone-door','treasure-chest','archive-shelf','tree-cut','rock-cut','jar-cut','sign-cut'].forEach(adventureImage);
const freshStats=()=>({lv:1,hp:40,max:40,exp:0,correct:0,total:0,streak:0,seen:[],wrong:[],potions:2});
let stats=freshStats(),battle=null,entryAt=0,fxUntil=0,flashUntil=0,ren={x:0,y:0,direction:'down',moving:false},trail=[],checkpoint=null;
const originalBackground=sceneBackground,originalSolids=activeSolid,originalBounds=outsideBounds,originalDraw=draw,originalMove=move,originalInspect=inspect,originalChange=changeScene,originalBegin=begin,originalRestore=restore,originalBlocked=blocked;
const prop=(image,x,y,w,h,solid=true)=>({image,x,y,w,h,solid});
function adventureProps(){switch(p.scene){
 case 'descent':return [];
 case 'entry':return story.collapsed?[prop('rock-cut',140,478,150,120),prop('rock-cut',280,485,160,120)]:[];
 case 'central':return [prop('jar-cut',360,320,48,66),...(story.collapsed?[prop('rock-cut',130,530,240,260),prop('rock-cut',235,570,150,180)]:[])];
 case 'archive':return [prop('archive-shelf',280,315,190,160),prop('archive-shelf',700,320,180,160),prop('treasure-chest',490,330,64,52)];
 case 'record':return [prop('archive-shelf',220,300,160,145),prop('archive-shelf',770,300,160,145)];
 case 'memory':return [prop('treasure-chest',240,320,64,52),prop('jar-cut',690,322,48,66)];
 case 'gate':return story.gateOpen?[]:[prop('stone-door',740,450,230,310)];
 case 'grass':return [prop('tree-cut',205,330,132,155),prop('rock-cut',340,340,80,72),prop('treasure-chest',450,568,64,52),prop('sign-cut',778,402,58,64),prop('distant-tower',595,173,106,175,false)];
 case 'village':return [prop('cottage',245,320,230,220),prop('village-shop',760,320,250,220),prop('cottage',480,235,185,174),prop('cottage',480,590,168,135),prop('sign-cut',100,420,58,64),prop('tree-cut',865,585,115,135),prop('tree-cut',105,275,110,130),prop('distant-tower',615,154,90,148,false)];
 case 'shop':return [prop('archive-shelf',220,290,150,125),prop('archive-shelf',745,290,150,125)];
 default:return [];
}}
function adventureNpcs(){if(p.scene==='village')return [{id:'couple',image:'elder-man',x:252,y:446},{id:'wife',image:'elder-woman',x:320,y:446},{id:'child',image:'village-child',x:560,y:432}];if(p.scene==='shop')return [{id:'keeper',image:'shopkeeper',x:480,y:344}];return []}
function nearPoint(x,y,r=82){return Math.hypot(p.x-x,p.y-y)<r}
function sprite(im,x,y,w,h){if(im.complete&&im.naturalWidth)g.drawImage(im,x-w/2,y-h,w,h)}
function drawRen(now){const im=adventureImage('ren-sheet');if(!im.complete||!im.naturalWidth)return;const a=DIRECTION_ANIMATIONS[ren.direction],cellW=im.naturalWidth/3,cellH=im.naturalHeight/4,frame=ren.moving?a.frames[Math.floor(now/(p.running?78:145))%4]:0;g.save();g.globalAlpha=.26;g.fillStyle='#172033';g.beginPath();g.ellipse(ren.x,ren.y+2,12,4,0,0,Math.PI*2);g.fill();g.globalAlpha=1;g.drawImage(im,frame*cellW,a.row*cellH,cellW,cellH,ren.x-50,ren.y-103,100,110);g.restore()}
function setRenBehind(){ren={x:p.x+(p.x<150?58:-58),y:p.y,direction:p.facingDirection,moving:false};trail=[{x:ren.x,y:ren.y,direction:ren.direction},{x:p.x,y:p.y,direction:p.facingDirection}]}
function followRen(){ren.moving=false;if(!story.renFollowing)return;if(p.moving)trail.push({x:p.x,y:p.y,direction:p.facingDirection});while(trail.length>1){let distance=0;for(let i=1;i<trail.length;i++)distance+=Math.hypot(trail[i].x-trail[i-1].x,trail[i].y-trail[i-1].y);if(distance<55)break;const point=trail.shift();ren.moving=Math.hypot(ren.x-point.x,ren.y-point.y)>.1;Object.assign(ren,{x:point.x,y:point.y,direction:point.direction})}}
sceneBackground=function(){return maps[p.scene]?adventureImage(maps[p.scene].image):originalBackground()};
activeSolid=function(){if(!maps[p.scene])return originalSolids();const solids=[[0,0,960,190],[0,600,960,40]];if(p.scene==='central'&&story.collapsed)solids.push([0,190,290,410]);for(const o of adventureProps()){if(!o.solid)continue;const baseHeight=o.image.includes('cottage')||o.image==='village-shop'?85:o.image==='archive-shelf'?42:o.image==='stone-door'?80:o.image==='tree-cut'?30:Math.min(36,o.h);solids.push([o.x-o.w*.38,o.y-baseHeight,o.w*.76,baseHeight])}for(const n of adventureNpcs())solids.push([n.x-12,n.y-8,24,16]);return solids};
outsideBounds=function(x,y){if(!maps[p.scene])return originalBounds(x,y);if(x<64||x>896||y<205||y>590)return true;/* Stone side openings meet at the same floor height in each map. */if(!['grass','village','archive','shop'].includes(p.scene)&&(x<92||x>860)&&(y<430||y>535))return true;return false};
// Reject entering solid feet rectangles even after reload or map arrival.
blocked=function(x,y){return maps[p.scene]?(outsideBounds(x,y)||insideSolid(x,y)):originalBlocked(x,y)};
function drawAdventure(now){const bg=sceneBackground();g.globalAlpha=1;g.globalCompositeOperation='source-over';g.filter='none';g.clearRect(0,0,960,640);if(bg.complete&&bg.naturalWidth)g.drawImage(bg,0,0,960,640);const layers=adventureProps().map(o=>({y:o.y,draw:()=>sprite(adventureImage(o.image),o.x,o.y,o.w,o.h)}));for(const n of adventureNpcs())layers.push({y:n.y,draw:()=>sprite(adventureImage(n.image),n.x,n.y,66,n.image==='village-child'?70:94)});if(story.renFollowing)layers.push({y:ren.y,draw:()=>drawRen(now)});if(p.scene==='record'&&!story.renFound)layers.push({y:465,draw:()=>{g.save();g.translate(520,456);g.rotate(-Math.PI/2);sprite(adventureImage('ren-front'),0,0,66,94);g.restore()}});layers.push({y:p.y,draw:()=>drawHero(now)});const enemy=fieldEnemy();if(enemy)layers.push({y:enemy.y,draw:()=>sprite(adventureImage(enemy.id==='bakuro'?'bakuro-small':'normal-enemy-field'),enemy.x,enemy.y,enemy.id==='bakuro'?68:48,enemy.id==='bakuro'?66:46)});layers.sort((a,b)=>a.y-b.y).forEach(l=>l.draw());if(p.scene==='record'&&!story.renFound){g.font='20px serif';g.fillStyle='#c7bb96';g.fillText('レン',555,473)}if(now<fxUntil){g.fillStyle='#4e466b';g.globalAlpha=.18;g.fillRect(0,0,960,640);g.globalAlpha=1}if(now<flashUntil&&room.complete){g.globalAlpha=.8;g.drawImage(room,0,0,960,640);sprite(girlLeft,480,495,108,160);g.globalAlpha=1}cv.setAttribute('aria-label',maps[p.scene].name);}
draw=function(now=performance.now()){if(maps[p.scene]){tickDialogue(now);drawAdventure(now);requestAnimationFrame(draw)}else originalDraw(now);hud.textContent='Lv '+stats.lv+'　HP '+stats.hp+'/'+stats.max+'　EXP '+stats.exp+(story.notebook?'　KEY '+(story.eraser?2:1):'');if(battle)drawBattle(now)};
function safeSave(){checkpoint={scene:p.scene,x:p.x,y:p.y,facingDirection:p.facingDirection,story:JSON.parse(JSON.stringify(story)),stats:JSON.parse(JSON.stringify(stats))};save()}
save=function(){try{localStorage.setItem(SAVE,JSON.stringify({name:p.name,story,stats,checkpoint}))}catch(e){console.warn('Save unavailable',e)}};
changeScene=function(scene,x,y,words){originalChange(scene,x,y,words);keys={};if(story.renFollowing)setRenBehind();if(scene==='entry')entryAt=performance.now();if(maps[scene])safeSave()};
function say(lines,done){p.moving=false;p.running=false;keys={};playDialogue(lines,()=>{save();if(done)done()})}
function descend(){story.underground=true;changeScene('descent',170,480);say(['主人公「少しだけ見てくる。」','女子生徒「……無理しないで。」','壁が、学校の白い壁から古びた石に変わっていく。','主人公「…………。」','主人公「学校じゃないだろ、これ。」'],safeSave)}
function fieldEnemy(){if(p.scene==='entry'&&!story.firstBattle&&performance.now()-entryAt>=30000)return {id:'first',x:630,y:480};if(p.scene==='corridor'&&!story.secondBattle)return {id:'second',x:580,y:480};if(p.scene==='joined'&&!story.coopBattle)return {id:'coop',x:570,y:480};if(p.scene==='memory'&&!story.lateBattle)return {id:'late',x:640,y:480};if(p.scene==='bakuro'&&!story.bakuroWon)return {id:'bakuro',x:560,y:480};return null}
function encounter(enemy){safeSave();if(enemy.id==='first')say(['床に散らばった文字が、ひとつの形に集まった。','主人公「……何だ？」','主人公「うわっ！」','問題に正解すると攻撃！　間違えると敵の攻撃！'],()=>startBattle('first',1));else if(enemy.id==='coop')say(['主人公「レン、下がってろ！」','レン「嫌だ。」','主人公「は？」','レン「一人より二人の方がいいだろ。」'],()=>startBattle('coop',3));else if(enemy.id==='bakuro')say(['主人公「……見ろ。」','レン「文字？」','主人公「集まってる。」','文字が奥へ流れ、大きな身体を形作った。','主人公「こいつ……。」','レン「さっきのやつとは違う。」','主人公「来るぞ！」'],()=>startBattle('bakuro',6));else startBattle(enemy.id,enemy.id==='second'?2:3)}
function findRen(){story.renFound=true;story.renFollowing=true;setRenBehind();say(['主人公「……人？」','主人公「おい。」','主人公「大丈夫？」','少年「…………。」','少年「ここ……。」','少年「どこ？」','主人公「俺が聞きたいよ。」','主人公「立てる？」','少年「たぶん。」','主人公「名前は？」','少年「…………。」','少年「名前。」','少年「俺の……名前……。」','少年「…………。」','少年「分からない。」','主人公「え？」','床の文字の中に、二文字だけはっきり残っている。','主人公「……レン？」','少年「レン。」','少年「…………。」','少年「たぶん、俺の名前。」','主人公「でも。」','主人公「これがお前の名前とは限らないだろ。」','少年「…………。」','少年「そうだな。」','少年「レンでいい。」','主人公「え？」','少年「他にないから。」','少年「思い出すまで、レンでいい。」','主人公「……分かった。」','主人公「他に覚えてることは？」','レン「…………。」','主人公「学校とか。」','レン「分からない。」','主人公「家は？」','レン「分からない。」','主人公「家族。」','レン「…………。」','レン「分からない。」','主人公「…………。」','主人公「とりあえず、一緒に戻ろう。」','レン「戻れる？」','主人公「来た道がある。」','主人公「学校に戻れば、誰かいるかもしれない。」','レン「学校？」','主人公「俺の学校。」','レン「…………。」','レン「分かった。」','主人公「こっちだ。」'],safeSave)}
function collapse(){story.collapsed=true;story.renJoined=true;fxUntil=performance.now()+900;say(['大きな音とともに、学校へ続く通路が崩れた。','主人公「うわっ！」','レン「下がって！」','主人公「…………。」','主人公「嘘だろ。」','完全に塞がっている。通れそうにない。','レン「戻れない？」','主人公「……今は無理だな。」','レン「じゃあ。」','レン「先に行くしかない。」','主人公「…………。」','主人公「だな。」','主人公「歩ける？」','レン「たぶん。」','主人公「それ好きだな。」','レン「何が？」','主人公「『たぶん』。」','レン「…………。」','レン「たぶん。」','主人公「…………。」'],()=>{p.x=310;safeSave()})}
function memoryScene(){story.memorySeen=true;fxUntil=performance.now()+1200;say(['主人公「レン。」','レン「何？」','主人公「……いや。」','レン「何だよ。」','主人公「呼んだら返事するんだなと思って。」','レン「名前なんだから当たり前だろ。」','主人公「たぶん、だけどな。」','レン「…………。」','主人公「悪い。」','レン「いや。」','レン「今は、レンでいい。」','主人公「そっか。」','レンが立ち止まった。','主人公「どうした？」','レン「…………。」','『レン。』','『忘れないで。』','主人公「レン？」','レン「今……。」','主人公「何？」','レン「声がした。」','主人公「声？」','レン「女の子の声。」','主人公「知ってる人？」','レン「…………。」','レン「分からない。」','主人公「何て？」','レン「『レン。』」','レン「それと。」','レン「『忘れないで。』」','主人公「…………。」','レン「これだけ。」','主人公「他には？」','レン「何も。」','主人公「そっか。」','レン「でも。」','主人公「ん？」','レン「知ってる声だった気がする。」','主人公「気がする？」','レン「……たぶん。」','主人公「またそれか。」','主人公「怖いな。」','レン「何が？」','主人公「忘れるって。」','レン「…………。」','レン「うん。」','主人公「忘れたことにも、気づけなくなる。」','レン「…………。」','レン「それが一番怖い。」'],safeSave)}
function arriveGrass(){story.grassStarted=true;say(['主人公「…………。」','レン「…………。」','主人公「学校の地下だったよな？」','レン「たぶん。」','主人公「それ禁止。」','レン「何が？」','主人公「『たぶん』。」','レン「……たぶん。」','主人公「…………。」','主人公「……あれ。」','レン「何？」','主人公「塔の周り。」','レン「鳥？」','主人公「…………。」','主人公「違う。」','レン「じゃあ何？」','主人公「文字……？」','レン「文字？」','主人公「分からない。」','主人公「……どうする。」','レン「どうするって？」','主人公「ここがどこかも分からない。」','レン「うん。」','主人公「学校に戻る道も分からない。」','レン「うん。」','主人公「お前は何も覚えてない。」','レン「それは言わなくてもいいだろ。」','主人公「事実だろ。」','レン「そうだけど。」','主人公「とりあえず、人を探そう。」','レン「人？」','主人公「誰かいれば、ここがどこか分かるかもしれない。」','レン「分かった。」','レン「それ？」','主人公「何？」','レン「ずっと持ってるやつ。」','主人公「国語のノート。」','レン「お前の？」','主人公「違う。」','主人公「借り物。」','レン「誰から？」','主人公「…………。」','主人公「クラスのやつ。」','レン「返さないと。」','主人公「分かってる。」','主人公「だから帰らないとな。」','レン「……うん。」'],safeSave)}
function villageSign(){story.signSeen=true;say(['道標「＿＿＿＿村　→」','主人公「…………。」','レン「どうした？」','主人公「ここ。」','レン「村？」','主人公「違う。」','主人公「村の名前。」','レン「読めない？」','主人公「……いや。」','主人公「読めないんじゃない。」','主人公「なくなってる。」','レン「名前が？」','主人公「たぶん。」','レン「……たぶん。」','主人公「それ俺の真似？」','レン「たぶん。」','レン「人、いるかな。」','主人公「いてくれないと困る。」','レン「何で？」','主人公「二人とも何も分かってないから。」','レン「俺は特に。」','主人公「自覚あるんだな。」','レン「それくらいは。」'],safeSave)}
function arriveVillage(){story.villageEntered=true;say(['―― 名前のない村 ――','入口の看板「＿＿＿＿村」','主人公「やっぱり、名前だけない。」','レン「村の人なら知ってるんじゃない？」','主人公「聞いてみよう。」','主人公「学校で言葉がおかしくなった。」','レン「うん。」','主人公「地下でも文字が消えてた。」','レン「うん。」','主人公「ここでも村の名前がない。」','レン「…………。」','主人公「同じことが起きてるのか？」','レン「分からない。」','主人公「でも。」','主人公「何か関係ありそうだな。」','レン「……あの塔？」','主人公「他に目立つものないし。」','レン「適当だな。」','主人公「手がかりゼロよりいいだろ。」'],safeSave)}
function shopTalk(){if(story.shopTalk){say(['店主「名前が出てこないんだ。けど、これは傷を治すものだよ。」']);return}story.shopTalk=true;say(['店主「いらっしゃい。」','店主「旅の人かい？」','主人公「たぶん。」','レン「うつった。」','主人公「うるさい。」','店主「必要なものがあったら言ってくれ。」','店主「それは……。」','店主「…………。」','店主「何だったかな。」','主人公「これ？」','店主「そう、それ。」','店主「傷を治す……。」','店主「…………。」','主人公「薬？」','店主「そう！」','店主「薬！」','店主「……いや。」','店主「薬なのは分かるんだ。」','店主「名前が出てこない。」','主人公「最近ずっと？」','店主「最近？」','店主「いや。」','店主「前は分かってた。」','店主「気づいたら、物の名前が出なくなってきた。」','レン「村の名前も？」','店主「…………。」','店主「村の名前？」','主人公「入口の看板。」','店主「ああ。」','店主「…………。」','店主「何だったかな。」'],safeSave)}
function childTalk(){if(story.childTalk){say(['子ども「一緒に遊ぶ人。家族じゃなくても、大事なんだね。」']);return}story.childTalk=true;say(['子ども「ねえ。」','主人公「何？」','子ども「『友達』って何？」','主人公「…………。」','主人公「え？」','子ども「友達。」','子ども「言葉は知ってる。」','子ども「でも。」','子ども「どういう意味だったっけ。」','主人公「一緒に遊んだり。」','主人公「話したり。」','主人公「そういう人。」','子ども「家族じゃない？」','主人公「家族じゃなくても。」','子ども「でも大事？」','主人公「……まあ。」','子ども「変なの。」'],()=>{if(story.shopTalk)forgettingTypes();else safeSave()})}
function forgettingTypes(){if(story.typesNoticed)return;story.typesNoticed=true;say(['レン「さっきの店の人と違う。」','主人公「何が？」','レン「店の人は、名前が出てこなかった。」','主人公「うん。」','レン「あの子は、言葉は覚えてた。」','レン「でも意味が分からなかった。」','主人公「…………。」','レン「忘れ方が違う。」','主人公「言葉が消えるだけじゃないってことか。」'],safeSave)}
function coupleTalk(){if(!story.shopTalk||!story.childTalk){say(['老人「少し待ってくれるかい。こちらの人と、話しているところなんだ。」']);return}if(story.coupleTalk){say(['妻「平気じゃないよ。でも、この人と暮らしてきたことは消えていない。」']);return}story.coupleTalk=true;say(['老人「すまない。」','老人「ちょっと聞いていいか。」','主人公「はい。」','老人「この人のことは分かる。」','老人「ずっと一緒に暮らしてきた。」','老人「顔も分かる。」','老人「一緒にいたことも分かる。」','老人「なのに。」','老人「名前だけがない。」','主人公「名前、忘れられて平気なんですか？」','妻「平気じゃないよ。」','妻「でもね。」',{text:'妻「忘れられる前に、もっと名前を呼んでおけばよかった。」',after:()=>{flashUntil=performance.now()+1300}},'アオイ『じゃあね。』','主人公「…………。」','レン「どうした？」','主人公「いや。」','主人公「何でもない。」'],()=>{story.decay=true;say(['入口の看板から、「村」という文字まで消えた。','主人公「……また消えた。」','レン「進んでる？」','主人公「……たぶん。」','レン「それ、俺の。」','主人公「うるさい。」'],()=>{story.phase='villagePause';safeSave()})})}
function adventureInspect(){if(p.scene==='archive'&&nearPoint(490,330,110)){if(story.eraser){say(['宝箱は空だ。']);return}story.eraser=true;say(['《古びた消しゴム》を手に入れた！','主人公「…………。」','主人公「消しゴム？」','かなり古い消しゴム。まだ少し使えそうだ。'],safeSave);return}if((p.scene==='central'&&nearPoint(360,320,100))||(p.scene==='memory'&&nearPoint(690,322,100))){const n=countInspect('pot');say(story.renFollowing?['レン「壺、好きなの？」','主人公「違う。」','レン「じゃあ、なんで全部調べるの？」','主人公「……なんとなく。」','レン「変なやつ。」']:n===1?['壺だ。']:n===2?['何もない。']:n===3?['本当に何もない。']:n===4?['だから何もない。']:['壺「…………。」','主人公「……ごめん。」']);return}if((p.scene==='memory'&&nearPoint(240,320,110))||(p.scene==='grass'&&nearPoint(450,568,95))){const key=p.scene+'Chest';if(story[key]){say(['宝箱は空だ。']);return}story[key]=true;stats.potions=Math.min(5,stats.potions+2);say(['回復薬 小を2個手に入れた。','HPを20回復する。戦闘中に使える。'],safeSave);return}if(p.scene==='archive'){say(['古い本が並んでいる。','文字はほとんど読めない。','主人公「ここも同じか……。」']);return}if(p.scene==='grass'){if(nearPoint(778,402,115)){villageSign();return}if(p.y>525&&!story.hillSeen){story.hillSeen=true;say(['主人公「でかいな……。」','レン「ここからでも、てっぺんがよく見えない。」','主人公「あれが何か知ってる？」','レン「…………。」','レン「分からない。」','主人公「だよな。」']);return}if(p.y<290){say(['北側の橋は壊れている。今は渡れない。']);return}}
 if(p.scene==='village'){const n=adventureNpcs().find(n=>nearPoint(n.x,n.y,92));if(n){if(n.id==='child')childTalk();else coupleTalk();return}if(nearPoint(100,420,100)){say([story.decay?'入口の看板「＿＿＿＿＿」':'入口の看板「＿＿＿＿村」']);return}if(p.y<340||p.y>520){say(['閉まっている。今は村の人に話を聞こう。']);return}}
 if(p.scene==='shop'){if(nearPoint(480,344,100)){shopTalk();return}}
 if(p.scene==='gate'&&!story.gateOpen&&p.x>590){story.gateOpen=true;say(['扉には、一つだけはっきり読める文章がある。','「記録されたものは、失われない。」','主人公「記録されたものは、失われない……。」','レン「どういう意味？」','主人公「分からない。」','主人公「覚えとこう。」','レン「うん。」','扉がゆっくり開く。隙間から、まぶしい光が差し込んでくる。','主人公「……外？」','レン「行ってみる？」','主人公「ここまで来たんだ。」','主人公「行こう。」'],safeSave);return}
 if(story.collapsed&&['entry','central'].includes(p.scene)&&p.x<330){say(['崩れた通路は、完全に塞がっている。','通れそうにない。']);return}say(['古い床に、小さなひびが走っている。']);}
inspect=function(){if(!started)return;if(dialogue.active){advanceDialogue();return}if(battle){if(battle.answered)advanceBattle();else answerBattle(battle.selected||0);return}if(p.scene==='right'&&story.stairsSeen&&p.x>590&&p.y<470){descend();return}if(maps[p.scene])adventureInspect();else originalInspect()};
move=function(){if(battle||dialogue.active||!started){p.moving=false;return}const before={x:p.x,y:p.y,scene:p.scene};originalMove();if(dialogue.active||battle)return;if(!maps[p.scene]){if(p.scene==='right'&&story.stairsSeen&&p.x>630&&p.y<415)descend();return}followRen();const e=fieldEnemy();if(e&&nearPoint(e.x,e.y,58)){encounter(e);return}
 if(p.scene==='descent'){if(p.x>860){changeScene('entry',110,480);say(['主人公「…………。」','主人公「どこまで続いてるんだ。」'],safeSave)}else if(p.x<76)changeScene('right',590,470);return}
 if(p.scene==='entry'){if(p.x>860){if(story.firstBattle)changeScene('corridor',110,p.y);else if(performance.now()-entryAt>=30000)encounter({id:'first'});else if(!story.entryExitNoticed){story.entryExitNoticed=true;say(['奥の床に、文字が集まり始めている。','主人公「……何かいる。少し様子を見よう。」'])}}else if(p.x<76&&!story.collapsed)changeScene('descent',820,p.y);return}
 if(p.scene==='corridor'){if(p.x>860){if(story.secondBattle)changeScene('central',110,p.y);else encounter({id:'second'})}else if(p.x<76)changeScene('entry',820,p.y);return}
 if(p.scene==='central'){if(story.renFound&&!story.collapsed&&p.x<270){collapse();return}if(p.x>860){changeScene(story.collapsed?'joined':'record',110,480);return}if(p.y<225&&p.x>420&&p.x<555){changeScene('archive',490,550);return}if(p.x<76&&!story.collapsed)changeScene('corridor',820,480);return}
 if(p.scene==='archive'){if(p.y>575)changeScene('central',480,260);return}
 if(p.scene==='record'){if(!story.renFound&&p.x>430){findRen();return}if(p.x<76)changeScene('central',820,480);return}
 if(p.scene==='joined'){if(p.x>250&&!story.renConversation){story.renConversation=true;say(['主人公「本当に何も覚えてないの？」','レン「…………。」','レン「ほとんど。」','主人公「学校も？」','レン「分からない。」','主人公「家も？」','レン「分からない。」','主人公「家族も？」','レン「…………。」','レン「分からない。」','主人公「そっか。」','レン「悪い。」','主人公「何が。」','レン「聞かれても、『分からない』しか言えない。」','主人公「別にいいだろ。」','レン「…………。」','主人公「思い出したら言えばいい。」','レン「……うん。」'],safeSave);return}if(p.x>860&&story.coopBattle)changeScene('memory',110,480);else if(p.x<76)changeScene('central',820,480);return}
 if(p.scene==='memory'){if(p.x>330&&!story.memorySeen){memoryScene();return}if(p.x>860&&story.lateBattle)changeScene('bakuro',110,480);else if(p.x<76)changeScene('joined',820,480);return}
 if(p.scene==='bakuro'){if(p.x>860&&story.bakuroWon)changeScene('gate',110,480);else if(p.x<76)changeScene('memory',820,480);return}
 if(p.scene==='gate'){if(p.x>860&&story.gateOpen){changeScene('grass',110,480);arriveGrass()}else if(p.x<76)changeScene('bakuro',820,480);return}
 if(p.scene==='grass'){if(p.x>650&&!story.signSeen){villageSign();return}if(p.x>860){changeScene('village',110,480);if(!story.villageEntered)arriveVillage()}else if(p.x<76)changeScene('gate',820,480);return}
 if(p.scene==='village'){if(story.childTalk&&story.shopTalk&&!story.typesNoticed){forgettingTypes();return}if(p.x>690&&p.x<820&&p.y<365){changeScene('shop',480,545);if(!story.shopTalk)shopTalk()}else if(p.x<76)changeScene('grass',820,480);return}
 if(p.scene==='shop'&&p.y>575)changeScene('village',755,370);
};
// All questions and choices are imported unchanged from the supplied 398-question bank.
const battlePanel=document.createElement('section');battlePanel.id='ch1-battle';battlePanel.hidden=true;battlePanel.innerHTML='<div id="battle-name"></div><div id="battle-art"></div><div id="battle-question"></div><div id="battle-choices"></div><div id="battle-feedback" aria-live="polite"></div><div id="battle-actions"><button id="battle-potion">回復薬 小（HP+20）</button><button id="battle-next" hidden>次へ</button></div>';document.querySelector('#app').append(battlePanel);
const uiStyle=document.createElement('style');uiStyle.textContent='#app{position:relative}#field{object-fit:contain}#ch1-battle{position:absolute;inset:46px 0 0;z-index:6;background:#10182a;display:flex;flex-direction:column;align-items:center;gap:8px;padding:14px;overflow:auto}#ch1-battle[hidden]{display:none}#battle-name{color:#fff0a9;font-size:17px}#battle-art{position:relative;width:100%;height:180px;flex-shrink:0;background-size:cover;background-position:center;image-rendering:pixelated}#battle-art img{position:absolute;object-fit:contain;image-rendering:pixelated}#battle-question,#battle-feedback{width:min(100%,800px);white-space:pre-line;line-height:1.5;padding:10px;border:2px solid #e0d4ad;background:#081329}#battle-choices{width:min(100%,800px);display:grid;grid-template-columns:1fr 1fr;gap:6px}#battle-choices button{text-align:left;min-height:46px}#battle-actions{display:flex;gap:12px}#battle-choices button.selected{background:#526fa1;border-color:#fff7b1;box-shadow:inset 0 0 0 2px #ffe7a1}#battle-feedback:empty{display:none}.attack{animation:attack .35s}.hurt{animation:hurt .4s}@keyframes attack{50%{transform:translateX(30px)}}@keyframes hurt{30%,70%{opacity:.2;transform:translateX(-7px)}}@media(max-width:600px){#ch1-battle{inset:42px 0 0;padding:8px;gap:5px}#battle-art{height:130px}#battle-choices{grid-template-columns:1fr}#battle-choices button{padding:8px;min-height:42px;font-size:13px}#battle-question,#battle-feedback{font-size:13px;padding:7px}#battle-name{font-size:14px}}';document.head.append(uiStyle);
const battleNames={first:'欠字獣',second:'欠字獣',coop:'文字の残滓',late:'文字の残滓',bakuro:'喰字獣バクロ'};
function startBattle(id,max){closeDialogueBox();keys={};battle={id,hp:max,max,q:0,answered:false,turn:0};battlePanel.hidden=false;const art=document.querySelector('#battle-art');art.style.backgroundImage='url(assets/kotoba-tower/'+maps[p.scene].image+'.webp)';art.innerHTML='<img id="battle-hero" src="assets/kotoba-tower/hero-current-battle.webp" style="left:8%;bottom:8px;width:70px;height:105px">'+(story.renJoined?'<img id="battle-ren" src="assets/kotoba-tower/ren-front.webp" style="left:20%;bottom:8px;width:66px;height:100px">':'')+'<img id="battle-enemy" src="assets/kotoba-tower/'+(id==='bakuro'?'bakuro-battle':'normal-enemy-battle')+'.webp" style="right:22%;bottom:12px;width:'+(id==='bakuro'?160:110)+'px;height:150px">';nextQuestion()}
function nextQuestion(){let ids=existingQuestions.map((_,i)=>i).filter(i=>!stats.seen.includes(i));if(!ids.length){ids=existingQuestions.map((_,i)=>i);if(stats.wrong.length)ids=[...new Set([...stats.wrong,...ids])]}const appropriate=ids.filter(i=>existingQuestions[i][4].level<=(battle.id==='bakuro'?2:1));if(appropriate.length)ids=appropriate;battle.selected=0;battle.q=ids[Math.floor(Math.random()*ids.length)];stats.seen.push(battle.q);battle.answered=false;const q=existingQuestions[battle.q];document.querySelector('#battle-name').textContent=battleNames[battle.id]+'　HP '+battle.hp+'/'+battle.max+'　あなた HP '+stats.hp+'/'+stats.max;document.querySelector('#battle-question').textContent=q[0];document.querySelector('#battle-feedback').textContent='';document.querySelector('#battle-next').hidden=true;const choices=document.querySelector('#battle-choices');choices.replaceChildren();q[1].forEach((text,i)=>{const b=document.createElement('button');b.textContent='ABCD'[i]+'　'+text;b.onclick=()=>answerBattle(i);choices.append(b)});markBattleChoice();updatePotion()}
function markBattleChoice(){document.querySelectorAll('#battle-choices button').forEach((b,i)=>b.classList.toggle('selected',i===(battle?.selected||0)))}
addEventListener('keydown',e=>{if(!battle||battle.answered||!e.key.startsWith('Arrow'))return;e.preventDefault();battle.selected=((battle.selected||0)+(e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1)+4)%4;markBattleChoice()});
function updatePotion(){const b=document.querySelector('#battle-potion');b.textContent='回復薬 小 ×'+stats.potions+'（HP+20）';b.disabled=!stats.potions||stats.hp>=stats.max||!!battle?.answered}
function animate(id,kind){const el=document.querySelector(id);if(!el)return;el.classList.remove('attack','hurt');void el.offsetWidth;el.classList.add(kind)}
function answerBattle(i){if(!battle||battle.answered)return;battle.answered=true;battle.turn++;document.querySelectorAll('#battle-choices button').forEach(b=>b.disabled=true);stats.total++;const q=existingQuestions[battle.q],ok=i===q[2];let words;if(ok){stats.correct++;stats.streak++;battle.hp=Math.max(0,battle.hp-1);animate('#battle-hero','attack');animate('#battle-enemy','hurt');words='正解！　主人公の攻撃！\n'+q[3]+'\n敵に1ダメージ。';if(story.renJoined&&battle.turn%2===0){animate('#battle-ren','attack');words+='\nレン「まだだ！」　追撃！'}stats.exp+=8}else{stats.streak=0;stats.hp=Math.max(0,stats.hp-5);stats.exp=Math.max(0,stats.exp-2);if(!stats.wrong.includes(battle.q))stats.wrong.push(battle.q);animate('#battle-enemy','attack');animate('#battle-hero','hurt');words='不正解。正解は「'+q[1][q[2]]+'」。\n'+q[3]+'\n敵の攻撃！　HPが5減った。意味を確かめて、もう一度考えよう。\nヒント：'+q[4].hints[0]+''}document.querySelector('#battle-feedback').textContent=words;document.querySelector('#battle-name').textContent=battleNames[battle.id]+'　HP '+battle.hp+'/'+battle.max+'　あなた HP '+stats.hp+'/'+stats.max;document.querySelector('#battle-next').hidden=false;document.querySelector('#battle-enemy').style.filter=battle.id==='bakuro'&&battle.hp<=2?'brightness(1.35)':battle.id==='bakuro'&&battle.hp<=4?'contrast(1.25)':'none';updatePotion();save()}
function advanceBattle(){if(!battle||!battle.answered)return;if(!stats.hp){const failed=battle.id;endBattle();stats.hp=stats.max;stats.streak=0;say(['力尽きた……。直前の安全な場所まで下がった。','HPが回復した。もう一度挑戦できる。'],()=>{p.x=Math.max(110,p.x-100);safeSave()});return}if(battle.hp>0){nextQuestion();return}const id=battle.id;endBattle();stats.exp+=id==='bakuro'?30:6;const oldLevel=stats.lv;if(id==='second'&&stats.lv===1)stats.exp=Math.max(30,stats.exp);while(stats.exp>=30+Math.pow(stats.lv-1,2)*12&&stats.lv<99){stats.exp-=30+Math.pow(stats.lv-1,2)*12;stats.lv++;stats.max+=5;stats.hp=stats.max}const levelWords=stats.lv>oldLevel?['LEVEL UP!　Lv.'+oldLevel+' → Lv.'+stats.lv,'最大HP UP　'+stats.max+'　攻撃力 UP　HP全回復！']:[];if(id==='first'){story.firstBattle=true;say(['欠字獣の身体が崩れ、文字が一瞬だけ並んだ。','ありがとう','主人公「…………。」','主人公「今……。」','主人公「『ありがとう』って……。」','主人公が近づこうとすると、文字は消えた。','主人公「消えた……。」',...levelWords],safeSave)}else if(id==='second'){story.secondBattle=true;say(['魔物を倒した。経験値を得た。',...levelWords],safeSave)}else if(id==='coop'){story.coopBattle=true;say(['主人公「戦えるの？」','レン「たぶん。」','主人公「またそれか。」','レン「でも勝った。」','主人公「……まあな。」',...levelWords],safeSave)}else if(id==='late'){story.lateBattle=true;say(['魔物を倒した。二人で先へ進もう。',...levelWords],safeSave)}else{story.bakuroWon=true;say(['バクロの身体から、大量の文字が抜けていく。','ありがとう　ごめんなさい　約束　友達　名前','主人公「これ……。」','レン「文字が戻ってる。」','主人公「消えてた言葉……？」','文字は光のようになり、どこかへ消えていった。','主人公「待って！」','レン「消えた……。」','主人公「いや。」','主人公「本当に消えてたなら、戻ってくるはずない。」','レン「じゃあ……。」','主人公「どこかに残ってる？」','巨大な身体が縮み、怯えた小さな生き物が残った。','レン「こいつ……。」','主人公「何だ？」','レン「怖がってる。」','主人公「え？」','レン「こいつも。」','レン「忘れてたんじゃないか。」','主人公「魔物なのに？」','レン「…………。」','レン「最初から魔物だったのかな。」','小さなバクロは、石の陰へ逃げていった。','主人公「敵を倒したら、言葉が出てきた。」','レン「うん。」','主人公「しかも、あいつまで変わった。」','レン「…………。」','主人公「何が起きてるんだ。」','レン「分からない。」','主人公「だよな。」','レン「でも。」','主人公「ん？」','レン「先に行けば、何か分かるかもしれない。」','主人公「……うん。」',...levelWords],safeSave)}}
function endBattle(){battle=null;battlePanel.hidden=true;keys={}}
function drawBattle(now){if(battle.id==='bakuro'&&battle.hp<=4){const el=document.querySelector('#battle-enemy');el.style.opacity=.9+Math.sin(now/180)*.1}}
document.querySelector('#battle-next').onclick=advanceBattle;document.querySelector('#battle-potion').onclick=()=>{if(!battle||battle.answered||!stats.potions)return;stats.potions--;stats.hp=Math.min(stats.max,stats.hp+20);document.querySelector('#battle-feedback').textContent='回復薬 小を使った。HPが20回復した。';updatePotion();save()};
restore=function(){originalRestore();try{const q=JSON.parse(localStorage.getItem(SAVE));if(q?.stats)stats={...freshStats(),...q.stats};checkpoint=q?.checkpoint||null}catch(e){}if(checkpoint){const b=document.createElement('button');b.textContent='続きから';b.onclick=()=>{story=JSON.parse(JSON.stringify(checkpoint.story));stats={...freshStats(),...checkpoint.stats};Object.assign(p,{scene:checkpoint.scene,x:checkpoint.x,y:checkpoint.y,facingDirection:checkpoint.facingDirection});started=true;title.style.display='none';if(story.renFollowing)setRenBehind();entryAt=performance.now();closeDialogueBox()};document.querySelector('#start').parentNode.append(b)}};
begin=function(){stats=freshStats();checkpoint=null;originalBegin()};document.querySelector('#start').onclick=begin;
addEventListener('blur',()=>{keys={}});document.addEventListener('visibilitychange',()=>{if(document.hidden)keys={}});
