const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'kt-prep-v022.html'),'utf8');
const source=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].at(-1)[1];
const elements=new Map();let frames=[],images=[],now=1000,drawn=[];
function el(id){if(elements.has(id))return elements.get(id);const value={id,textContent:'',value:'',style:{},dataset:{},children:[],hidden:false,classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},append(x){this.children.push(x)},replaceChildren(){this.children=[]},parentNode:{append(){}},offsetWidth:1};Object.defineProperty(value,'innerHTML',{set(v){value.html=v;for(const m of v.matchAll(/id="([^"]+)"/g))el('#'+m[1])}});elements.set(id,value);return value}
const g=new Proxy({drawImage(im){assert(im.complete&&im.naturalWidth,'Drawing undecoded image');drawn.push(im.src)}},{get:(o,k)=>o[k]||(()=>{})});el('#field').getContext=()=>g;
const storage=new Map(),context={console,performance:{now:()=>now},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Image:class{constructor(){this.complete=true;this.naturalWidth=960;this.naturalHeight=640;images.push(this)}set src(v){this.url=v;assert(fs.existsSync(path.join(root,v)),`Missing asset ${v}`)}get src(){return this.url}addEventListener(){}},document:{querySelector:el,querySelectorAll:s=>s==='#battle-choices button'?el('#battle-choices').children:[],createElement:()=>el('created-'+Math.random()),head:{append(){}},addEventListener(){}},addEventListener(){},requestAnimationFrame:f=>frames.push(f),setInterval(){},setTimeout(){},clearTimeout(){},Math};context.window=context;vm.createContext(context);
const instrument=fs.readFileSync(path.join(__dirname,'ch1-test-bridge.inc.js'),'utf8');vm.runInContext(source.replace(' restore();setInterval(move,16);draw();',instrument+'\n restore();setInterval(move,16);draw();'),context);
const check=require('./ch1-check-flow.js');const result=check(context.__ch1Test,(ok,message)=>assert(ok,message),scene=>{drawn=[];context.__ch1Test.draw(now+=1000);assert(drawn.length>=2,`Background and sprites in ${scene}`)});
console.log('PASS',JSON.stringify(result));
