/* Ranking service: no CDN, no names in network payloads, explicit opt-in. */
(function(root){'use strict';
const VERSION='scope-20261007-v1',CONFIG_URL='kotoba-ranking/firebase-config.json';
function hash(text){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
function challenge(engine,scope,category){const pool=engine.questionPool().filter(q=>(category==='すべて'||q.category===category)&&(scope==='scope'?engine.questionPriority(q)<2:scope==='original'?engine.data.questions.some(o=>o.id===q.id):true));const priority=q=>scope==='original'?0:engine.questionPriority(q),seed=VERSION+'|'+scope+'|'+category;pool.sort((a,b)=>priority(a)-priority(b)||hash(seed+'|'+a.id).localeCompare(hash(seed+'|'+b.id))||a.id.localeCompare(b.id));const words=new Set(),list=[];for(const q of pool){const key=q.category+'|'+(q.word||q.id);if(words.has(key))continue;words.add(key);list.push(q);if(list.length===20)break;}
 const signature=list.map(q=>q.id+'|'+q.prompt+'|'+q.choices.join('|')+'|'+q.answer).join('\n');return {id:'c-'+hash(seed+'|'+signature),label:({'priority':'テスト範囲優先','scope':'テスト範囲のみ','original':'従来の398問'}[scope]||scope)+'／'+category,total:list.length,list,version:VERSION};}
function ranks(entries){const sorted=[...entries].sort((a,b)=>b.correct-a.correct||a.studentId.localeCompare(b.studentId));let rank=0,last=-1;return sorted.map((e,i)=>{if(e.correct!==last)rank=i+1;last=e.correct;return {...e,rank};});}
function cleanNickname(value){const s=String(value||'').normalize('NFKC').trim();if(!s||Array.from(s).length>12||/[\x00-\x1f\x7f]/.test(s))throw Error('ニックネームは1～12文字で入力してください。本名は使わないでください。');return s;}
function parseCode(value){const parts=String(value||'').trim().split('.');if(parts.length!==2||!/^K[A-F0-9]{8}$/.test(parts[0])||! /^[a-f0-9]{32}$/.test(parts[1]))throw Error('先生から受け取った参加コードを確認してください。');return {studentId:parts[0],token:parts[1]};}
function fields(value){return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,typeof v==='number'?{integerValue:String(v)}:typeof v==='boolean'?{booleanValue:v}:{stringValue:String(v)}]));}
function unpack(doc){return Object.fromEntries(Object.entries(doc.fields||{}).map(([k,v])=>[k,v.integerValue!==undefined?Number(v.integerValue):v.booleanValue!==undefined?v.booleanValue:v.stringValue]));}
function createClient({config=null,fetcher=root.fetch?.bind(root),storage,role='student',now=()=>Date.now()}={}){
 if(storage===undefined)try{storage=root.localStorage;}catch(e){storage=null;}
 let settings=config,auth=null,loading=null,authenticating=null;const key='kotoba-ranking-v1-'+role;let identity=null,pending=[];try{identity=JSON.parse(storage.getItem(key+'-identity')||'null');pending=JSON.parse(storage.getItem(key+'-pending')||'[]');}catch(e){}if(!Array.isArray(pending))pending=[];
 function keep(){try{if(role==='student'){storage.setItem(key+'-identity',JSON.stringify(identity));storage.setItem(key+'-pending',JSON.stringify(pending));}return true;}catch(e){return false;}}
 async function request(url,options={}){if(!fetcher)throw Error('この端末では通信を利用できません。');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetcher(url,{...options,signal:controller.signal});let body;try{body=await r.json();}catch(e){throw Error('通信先から正しい応答がありません。');}if(!r.ok){const code=body.error?.message||body.error?.status||String(r.status);if(/PERMISSION_DENIED|INSUFFICIENT_PERMISSION/.test(code))throw Error('参加登録または教師権限を確認してください。');if(/INVALID_LOGIN_CREDENTIALS|INVALID_PASSWORD|EMAIL_NOT_FOUND/.test(code))throw Error('教師のメールアドレス・パスワードを確認してください。');if(/RESOURCE_EXHAUSTED|QUOTA_EXCEEDED|TOO_MANY_ATTEMPTS/.test(code))throw Error('送信上限に達しました。時間をおいて再試行してください。');throw Error('通信できませんでした（'+code+'）。');}return body;}catch(e){if(e.name==='AbortError')throw Error('通信が時間内に完了しませんでした。後で再試行してください。');throw e;}finally{clearTimeout(timer);}}
 async function ready(){if(settings?.enabled&&settings.apiKey&&settings.projectId&&settings.classId)return settings;if(loading)return loading;loading=(async()=>{if(root.location?.protocol==='file:')throw Error('ランキングは公開URLから利用してください。通常練習はこのファイルでも遊べます。');const value=await request(CONFIG_URL,{cache:'no-store'});if(!value.enabled||!value.apiKey||!value.projectId||!value.classId)throw Error('共有ランキングはFirebase接続の準備中です。通常練習・20問挑戦は利用できます。');if(!/^[a-z0-9-]+$/.test(value.projectId)||! /^[A-Za-z0-9_-]{1,60}$/.test(value.classId))throw Error('ランキングの接続設定が正しくありません。');settings=value;return settings;})().finally(()=>loading=null);return loading;}
 function accept(a){auth={idToken:a.idToken||a.id_token,refreshToken:a.refreshToken||a.refresh_token,uid:a.localId||a.user_id,expires:now()+Number(a.expiresIn||a.expires_in||3600)*1000-60000};if(role==='student')try{storage.setItem(key+'-auth',JSON.stringify({...auth,projectId:settings.projectId,classId:settings.classId}));}catch(e){}return auth;}
 async function session(){await ready();if(auth&&auth.expires>now())return auth;if(authenticating)return authenticating;authenticating=(async()=>{if(!auth&&role==='student')try{const old=JSON.parse(storage.getItem(key+'-auth')||'null');if(old?.projectId===settings.projectId&&old?.classId===settings.classId)auth=old;}catch(e){}if(auth&&auth.expires>now())return auth;if(auth?.refreshToken){const a=await request('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(settings.apiKey),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:auth.refreshToken}).toString()});return accept(a);}if(role==='teacher')throw Error('先に教師用アカウントでログインしてください。');return accept(await request('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(settings.apiKey),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})}));})().finally(()=>authenticating=null);return authenticating;}
 async function login(email,password){await ready();const a=await request('https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key='+encodeURIComponent(settings.apiKey),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});accept(a);await get('teachers/'+auth.uid);return auth.uid;}
 function path(p){return 'https://firestore.googleapis.com/v1/projects/'+settings.projectId+'/databases/(default)/documents/classes/'+settings.classId+'/'+p;}
 async function api(p,options={}){const a=await session();return request(path(p),{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+a.idToken,...options.headers}});}
 async function get(p){return unpack(await api(p));}
 async function put(p,value,createOnly=false){return api(p+(createOnly?'?currentDocument.exists=false':''),{method:'PATCH',body:JSON.stringify({fields:fields(value)})});}
 async function join(code,nickname){const id=parseCode(code),nick=cleanNickname(nickname);await session();await put('bindings/'+auth.uid,id);identity={...id,nickname:nick,projectId:settings.projectId,classId:settings.classId};keep();return {studentId:id.studentId,nickname:nick};}
 async function ensureMember(){if(!identity)throw Error('先生の参加コードとニックネームを登録してください。');await session();if(identity.projectId!==settings.projectId||identity.classId!==settings.classId)throw Error('このクラスの参加コードを登録してください。');await put('bindings/'+auth.uid,{studentId:identity.studentId,token:identity.token});}
 async function send(item){const owner=identity;await ensureMember();if(identity!==owner)throw Error('参加登録が変わったため送信を中止しました。');const total=item.total,correct=item.correct;if(!Number.isInteger(total)||total<1||total>20||!Number.isInteger(correct)||correct<0||correct>total||! /^c-[a-f0-9]{8}$/.test(item.board))throw Error('得点データが正しくありません。');const p='boards/'+item.board+'/entries/'+identity.studentId;let previous=null;try{previous=await get(p);}catch(e){if(!e.message.includes('NOT_FOUND'))throw e;}if(identity!==owner)throw Error('参加登録が変わったため送信を中止しました。');if(previous&&previous.correct>correct)return {keptBest:true};await put(p,{studentId:identity.studentId,nickname:cleanNickname(identity.nickname),correct,total,version:VERSION});return {keptBest:false};}
 function queue(item){if(!identity)throw Error('結果を送信する前に参加登録してください。');const bound={board:item.board,correct:item.correct,total:item.total,studentId:identity.studentId,projectId:identity.projectId,classId:identity.classId};const same=pending.findIndex(p=>p.board===bound.board&&p.studentId===bound.studentId&&p.projectId===bound.projectId&&p.classId===bound.classId);if(same>=0){if(pending[same].correct<=bound.correct)pending[same]=bound;}else pending.push(bound);if(pending.length>100)pending=pending.slice(-100);return keep();}
 async function flush(){if(!identity)throw Error('先に参加登録してください。');let sent=0;for(const item of [...pending]){if(item.studentId!==identity.studentId||item.projectId!==identity.projectId||item.classId!==identity.classId)continue;await send(item);pending=pending.filter(p=>p!==item);keep();sent++;}return sent;}
 async function submit(item){const persisted=queue(item);try{await flush();return {ok:true,persisted};}catch(e){return {ok:false,persisted,error:e.message};}}
 async function board(id){const result=await api('boards/'+id+':runQuery',{method:'POST',body:JSON.stringify({structuredQuery:{from:[{collectionId:'entries'}],orderBy:[{field:{fieldPath:'correct'},direction:'DESCENDING'}],limit:200}})});return ranks(result.filter(r=>r.document).map(r=>unpack(r.document)));}
 async function provision(student){return put('students/'+student.studentId,{token:student.token,active:true},true);}
 async function provisionBoard(b){return put('boards/'+b.id,{total:b.total,version:VERSION,label:b.label});}
 return {ready,join,submit,flush,board,login,provision,provisionBoard,get identity(){return identity&&{studentId:identity.studentId,nickname:identity.nickname}},get pendingCount(){return pending.filter(p=>p.studentId===identity?.studentId&&p.projectId===identity?.projectId&&p.classId===identity?.classId).length;},logout(){auth=null;},get settings(){return settings;}};
}
function randomHex(bytes){const a=new Uint8Array(bytes);root.crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('');}
function roster(names){return names.map(name=>({studentId:'K'+randomHex(4).toUpperCase(),token:randomHex(16),name:String(name).trim()}));}
function download(value,filename){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const api={VERSION,challenge,ranks,cleanNickname,parseCode,createClient,roster,download,hash};if(typeof module!=='undefined')module.exports=api;else root.KotobaRanking=api;
})(globalThis);
