'use strict';
(()=>{const $=id=>document.getElementById(id),R=KotobaRanking,client=R.createClient({role:'teacher',fetcher:(url,opts)=>fetch(url=== 'kotoba-ranking/firebase-config.json'?'firebase-config.json':url,opts)});let roster=[],boards=[],entries=[],logged=false,savedRoster=false,busy=false;
function status(text){$('status').textContent=text;}
function controls(){for(const id of ['register','initBoards','scores'])$(id).disabled=!logged||busy||(id==='register'&&!roster.length);$('saveRoster').disabled=!roster.length;$('cardsButton').disabled=!roster.length||!savedRoster;$('exportScores').disabled=!entries.length;}
async function work(task){if(busy)return;busy=true;controls();try{await task();}catch(e){status(e.message);}finally{busy=false;controls();}}
function setRoster(list){if(!Array.isArray(list)||!list.length||list.length>200)throw Error('名簿は1～200人で指定してください。');const ids=new Set();for(const s of list){R.parseCode(s.studentId+'.'+s.token);if(ids.has(s.studentId)||typeof s.name!=='string'||!s.name.trim()||s.name.length>80)throw Error('名簿のIDまたは氏名を確認してください。');ids.add(s.studentId);}roster=list.map(s=>({studentId:s.studentId,token:s.token,name:s.name}));$('rosterSummary').textContent=roster.length+'人の名簿を読み込みました。';entries=[];$('scoreTable').replaceChildren();controls();}
$('makeRoster').onclick=()=>{try{if(roster.length&&!confirm('現在の名簿を保存しましたか？ 新しいIDと参加コードを作ります。'))return;const names=$('names').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);setRoster(R.roster(names));savedRoster=false;controls();status('教師用名簿を保存してから、参加コードを登録してください。');}catch(e){status(e.message);}};
$('saveRoster').onclick=()=>{R.download({format:'kotoba-teacher-roster-v1',classId:client.settings?.classId||'kotoba-2026',students:roster},'コトバの塔_教師用名簿_非公開_'+new Date().toISOString().slice(0,10)+'.json');savedRoster=true;controls();status('教師用名簿を保存しました。本人の参加カードだけを配付してください。');};
$('rosterFile').onchange=async ev=>{try{const f=ev.target.files[0];if(!f)return;if(f.size>1048576)throw Error('名簿ファイルが大きすぎます。');const v=JSON.parse(await f.text());if(v.format!=='kotoba-teacher-roster-v1')throw Error('教師用名簿の形式ではありません。');if(client.settings?.enabled&&v.classId!==client.settings.classId)throw Error('別のクラスの名簿です。');setRoster(v.students);savedRoster=true;controls();status('保存した教師用名簿を読み込みました。');}catch(e){status(e.message);}ev.target.value='';};
$('login').onclick=()=>work(async()=>{const uid=await client.login($('email').value.trim(),$('password').value);$('password').value='';logged=true;status('教師としてログインしました。');controls();});
$('logout').onclick=()=>{client.logout();logged=false;entries=[];$('scoreTable').replaceChildren();$('password').value='';controls();status('ログアウトしました。');};
$('register').onclick=()=>work(async()=>{if(!savedRoster)throw Error('先に教師用名簿を保存してください。');let count=0;for(const s of roster){try{await client.provision(s);}catch(e){if(!e.message.includes('ALREADY_EXISTS'))throw e;const old=await client.get('students/'+s.studentId);if(old.token!==s.token)throw Error('同じIDに別の参加コードが登録されています。名簿を確認してください。');}status('参加コードの登録 '+(++count)+' / '+roster.length);}status(roster.length+'人の参加コードを登録しました。氏名は送信していません。');});
$('initBoards').onclick=()=>work(async()=>{let n=0;for(const b of boards){await client.provisionBoard(b);status('問題セットの登録 '+(++n)+' / '+boards.length);}status('問題セットを登録しました。生徒が挑戦結果を送信できます。');});
$('cardsButton').onclick=()=>{const list=$('cardList');list.replaceChildren();for(const s of roster){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p'),code=document.createElement('code');h.textContent=s.name+' さん用';p.textContent='公開ID：'+s.studentId+' ／ 本名を使わないニックネームを登録してください。参加コードは本人だけで使います。';code.textContent=s.studentId+'.'+s.token;article.append(h,p,code);list.append(article);}$('cards').classList.remove('hidden');$('cards').scrollIntoView();};
$('scores').onclick=()=>work(async()=>{const b=boards.find(x=>x.id===$('board').value);if(!b)throw Error('問題セットを選んでください。');entries=await client.board(b.id);const table=document.createElement('table'),head=document.createElement('tr');for(const v of ['順位','ID','ニックネーム','氏名（教師のみ）','正答数']){const th=document.createElement('th');th.textContent=v;head.append(th);}table.append(head);for(const e of entries){const tr=document.createElement('tr');for(const v of [e.rank,e.studentId,e.nickname,roster.find(s=>s.studentId===e.studentId)?.name||'名簿未照合',e.correct+' / '+e.total]){const td=document.createElement('td');td.textContent=String(v);tr.append(td);}table.append(tr);}$('scoreTable').replaceChildren(table);status(b.label+' ／ '+entries.length+'人。氏名は教師用名簿から、この端末で照合しています。');});
function csvCell(v){let s=String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('exportScores').onclick=()=>{const rows=[['順位','ID','ニックネーム','氏名','正答数','問題数'],...entries.map(e=>[e.rank,e.studentId,e.nickname,roster.find(s=>s.studentId===e.studentId)?.name||'',e.correct,e.total])];const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='コトバの塔_教師用得点_非公開_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
fetch('challenges.json').then(r=>{if(!r.ok)throw Error('問題セットを読み込めません。');return r.json();}).then(list=>{boards=list;for(const b of boards){const o=document.createElement('option');o.value=b.id;o.textContent=b.label+'（'+b.total+'問）';$('board').append(o);}}).catch(e=>status(e.message));controls();
})();
